version: 1.0.{build}
image: Visual Studio 2017
configuration: Debug
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  project: ColorSet.sln
  verbosity: minimal
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: '#ci'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
